package fargate

import (
	"strings"
	"testing"

	"github.com/aws/aws-sdk-go-v2/aws"
	cloudwatchlogstypes "github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs/types"
	ecstypes "github.com/aws/aws-sdk-go-v2/service/ecs/types"

	"github.com/backflow-labs/backflow/internal/config"
	"github.com/backflow-labs/backflow/internal/models"
	"github.com/backflow-labs/backflow/internal/orchestrator"
)

// Compile-time check: *Manager must satisfy orchestrator.Runner.
var _ orchestrator.Runner = (*Manager)(nil)

func TestFargateBuildECSEnvVars(t *testing.T) {
	manager := NewManager(&config.Config{
		AuthMode:        config.AuthModeAPIKey,
		AnthropicAPIKey: "sk-ant",
		OpenAIAPIKey:    "sk-openai",
		GitHubToken:     "ghp-test",
	}, nil)

	task := &models.Task{
		ID:             "bf_01ABC",
		TaskMode:       models.TaskModeReview,
		Harness:        models.HarnessCodex,
		RepoURL:        "https://github.com/test/repo",
		Branch:         "feature/test",
		TargetBranch:   "main",
		ReviewPRURL:    "https://github.com/test/repo/pull/42",
		ReviewPRNumber: 42,
		Prompt:         "Review this PR",
		Context:        "Focus on auth changes",
		Model:          "gpt-5.4-mini",
		Effort:         "high",
		MaxBudgetUSD:   7.5,
		MaxTurns:       80,
		CreatePR:       true,
		SelfReview:     true,
		PRTitle:        "Review auth changes",
		PRBody:         "Generated by Backflow",
		ClaudeMD:       "Additional instructions",
		EnvVars: map[string]string{
			"BETA_FLAG": "1",
			"ZZZ_LAST":  "done",
		},
	}

	envVars := manager.buildECSEnvVars(task)
	got := make(map[string]string, len(envVars))
	for _, pair := range envVars {
		got[aws.ToString(pair.Name)] = aws.ToString(pair.Value)
	}

	want := map[string]string{
		"TASK_ID":           "bf_01ABC",
		"TASK_MODE":         models.TaskModeReview,
		"HARNESS":           string(models.HarnessCodex),
		"REPO_URL":          "https://github.com/test/repo",
		"BRANCH":            "feature/test",
		"TARGET_BRANCH":     "main",
		"REVIEW_PR_URL":     "https://github.com/test/repo/pull/42",
		"REVIEW_PR_NUMBER":  "42",
		"PROMPT":            "Review this PR",
		"MODEL":             "gpt-5.4-mini",
		"EFFORT":            "high",
		"MAX_BUDGET_USD":    "7.5",
		"MAX_TURNS":         "80",
		"CREATE_PR":         "true",
		"SELF_REVIEW":       "true",
		"AUTH_MODE":         string(config.AuthModeAPIKey),
		"PR_TITLE":          "Review auth changes",
		"PR_BODY":           "Generated by Backflow",
		"CLAUDE_MD":         "Additional instructions",
		"TASK_CONTEXT":      "Focus on auth changes",
		"ANTHROPIC_API_KEY": "sk-ant",
		"OPENAI_API_KEY":    "sk-openai",
		"GITHUB_TOKEN":      "ghp-test",
		"BETA_FLAG":         "1",
		"ZZZ_LAST":          "done",
	}

	for key, wantValue := range want {
		if got[key] != wantValue {
			t.Errorf("%s = %q, want %q", key, got[key], wantValue)
		}
	}
}

func TestFargateMapECSTaskStatus(t *testing.T) {
	tests := []struct {
		name      string
		task      ecstypes.Task
		wantDone  bool
		wantCode  int
		wantError string
		wantFail  bool
	}{
		{
			name:     "running task",
			task:     ecstypes.Task{LastStatus: aws.String("RUNNING"), Containers: []ecstypes.Container{{Name: aws.String("backflow-agent")}}},
			wantDone: false,
		},
		{
			name:     "stopped success",
			task:     ecstypes.Task{LastStatus: aws.String("STOPPED"), Containers: []ecstypes.Container{{Name: aws.String("backflow-agent"), ExitCode: aws.Int32(0)}}},
			wantDone: true,
			wantCode: 0,
		},
		{
			name:      "stopped failure",
			task:      ecstypes.Task{LastStatus: aws.String("STOPPED"), Containers: []ecstypes.Container{{Name: aws.String("backflow-agent"), ExitCode: aws.Int32(137)}}},
			wantDone:  true,
			wantCode:  137,
			wantError: "container exited with code 137",
		},
		{
			name:      "stopped before container exit code available",
			task:      ecstypes.Task{LastStatus: aws.String("STOPPED"), StoppedReason: aws.String("Task failed to start")},
			wantDone:  true,
			wantError: "Task failed to start",
		},
		{
			name:     "unknown status",
			task:     ecstypes.Task{LastStatus: aws.String("MYSTERY")},
			wantFail: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			status, err := mapECSTaskStatus(tt.task, "backflow-agent")
			if tt.wantFail {
				if err == nil {
					t.Fatal("expected error, got nil")
				}
				return
			}
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if status.Done != tt.wantDone {
				t.Errorf("Done = %v, want %v", status.Done, tt.wantDone)
			}
			if status.ExitCode != tt.wantCode {
				t.Errorf("ExitCode = %d, want %d", status.ExitCode, tt.wantCode)
			}
			if status.Error != tt.wantError {
				t.Errorf("Error = %q, want %q", status.Error, tt.wantError)
			}
		})
	}
}

func TestFargateParseStatusFromLogEvents(t *testing.T) {
	events := []cloudwatchlogstypes.OutputLogEvent{
		{Message: aws.String("==> starting")},
		{Message: aws.String(`BACKFLOW_STATUS_JSON:{"needs_input":true,"question":"Which region?","complete":false,"error":"waiting on input","pr_url":"https://github.com/test/repo/pull/1"}`)},
	}

	status, ok := parseStatusFromLogEvents(events)
	if !ok {
		t.Fatal("expected status JSON to be parsed")
	}
	if !status.NeedsInput {
		t.Error("NeedsInput = false, want true")
	}
	if status.Question != "Which region?" {
		t.Errorf("Question = %q, want %q", status.Question, "Which region?")
	}
	if status.Error != "waiting on input" {
		t.Errorf("Error = %q, want %q", status.Error, "waiting on input")
	}
	if status.PRURL != "https://github.com/test/repo/pull/1" {
		t.Errorf("PRURL = %q, want PR URL", status.PRURL)
	}
	if status.Complete {
		t.Error("Complete = true, want false")
	}
}

func TestFargateParseStatusFromLogEvents_Complete(t *testing.T) {
	events := []cloudwatchlogstypes.OutputLogEvent{
		{Message: aws.String("==> running agent")},
		{Message: aws.String(`BACKFLOW_STATUS_JSON:{"needs_input":false,"question":"","complete":true,"error":"","pr_url":"https://github.com/test/repo/pull/5"}`)},
	}

	status, ok := parseStatusFromLogEvents(events)
	if !ok {
		t.Fatal("expected status JSON to be parsed")
	}
	if !status.Complete {
		t.Error("Complete = false, want true")
	}
	if status.NeedsInput {
		t.Error("NeedsInput = true, want false")
	}
	if status.PRURL != "https://github.com/test/repo/pull/5" {
		t.Errorf("PRURL = %q, want PR URL", status.PRURL)
	}
}

func TestFargateParseStatusFromLogEvents_EscapedMultilineError(t *testing.T) {
	events := []cloudwatchlogstypes.OutputLogEvent{
		{Message: aws.String(`BACKFLOW_STATUS_JSON:{"needs_input":false,"question":"","complete":false,"error":"line 1\nline 2: model_not_found","pr_url":""}`)},
	}

	status, ok := parseStatusFromLogEvents(events)
	if !ok {
		t.Fatal("expected status JSON to be parsed")
	}
	if status.Error == "" {
		t.Fatal("expected error text to be preserved")
	}
	if !strings.Contains(status.Error, "model_not_found") {
		t.Errorf("Error = %q, want model_not_found to be preserved", status.Error)
	}
}

func TestFargateBuildLogStreamName(t *testing.T) {
	manager := NewManager(&config.Config{
		ECSContainerName:   "backflow-agent",
		ECSLogStreamPrefix: "ecs",
	}, nil)

	tests := []struct {
		name    string
		taskARN string
		want    string
		wantErr bool
	}{
		{name: "short task arn", taskARN: "arn:aws:ecs:us-east-1:123456789012:task/0123456789abcdef", want: "ecs/backflow-agent/0123456789abcdef"},
		{name: "long task arn", taskARN: "arn:aws:ecs:us-east-1:123456789012:task/backflow/0123456789abcdef", want: "ecs/backflow-agent/0123456789abcdef"},
		{name: "invalid arn", taskARN: "not-an-arn", wantErr: true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := manager.buildLogStreamName(tt.taskARN)
			if tt.wantErr {
				if err == nil {
					t.Fatal("expected error, got nil")
				}
				return
			}
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if got != tt.want {
				t.Errorf("buildLogStreamName() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestEstimateOverridesSize(t *testing.T) {
	vars := []ecstypes.KeyValuePair{
		ecsEnvVar("TASK_ID", "bf_01ABC"),
		ecsEnvVar("PROMPT", "Fix the bug"),
	}
	size := estimateOverridesSize(vars)
	if size < 200 || size > 500 {
		t.Errorf("estimateOverridesSize = %d, expected roughly 293", size)
	}
}

func TestOffloadLargeEnvVarsSkipsWhenSmall(t *testing.T) {
	manager := NewManager(&config.Config{}, nil)
	vars := []ecstypes.KeyValuePair{
		ecsEnvVar("TASK_ID", "bf_01ABC"),
		ecsEnvVar("PROMPT", "Fix the bug"),
	}
	result, err := manager.offloadLargeEnvVars(nil, "bf_01ABC", vars)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(result) != len(vars) {
		t.Errorf("expected %d vars, got %d", len(vars), len(result))
	}
	for _, v := range result {
		if aws.ToString(v.Name) == "PROMPT" && aws.ToString(v.Value) != "Fix the bug" {
			t.Errorf("PROMPT was unexpectedly modified")
		}
	}
}

func TestIsSpotInterruptionReason(t *testing.T) {
	tests := []struct {
		name   string
		reason string
		want   bool
	}{
		{"empty", "", false},
		{"normal stop", "Essential container in task exited", false},
		{"user stop", "stopped by backflow", false},
		{"scaling activity", "Scaling activity initiated by deployment", false},
		{"ec2 spot terminated", "Host EC2 (spot) terminated", true},
		{"ec2 spot terminated lowercase", "host ec2 (spot) terminated", true},
		{"fargate spot capacity", "Your Fargate Spot capacity reclaimed", true},
		{"spot capacity generic", "Spot capacity unavailable", true},
		{"task failed to start", "Task failed to start", false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := isSpotInterruptionReason(tt.reason)
			if got != tt.want {
				t.Errorf("isSpotInterruptionReason(%q) = %v, want %v", tt.reason, got, tt.want)
			}
		})
	}
}
